### ISSUE TITLE
Interfaces COO 

### ISSUE THREAD

**Issue by DiegoBP12** [NeoxTec/quetzalStock#23]
Diseñará y Desarrollará 4 de las interfaces del sistema (Compras, Detalles Compra, Consulta Ventas, Catalogo).

**Comment by MarioAlbertoNL1799** [comment]
Wireframes asignadas ya están finalizadas.
Todas las interfaces de los issues #20 #21 #22 y #23 estan localizadas en un documento pdf ubicado en [https://github.com/NeoxTec/quetzalStock/blob/master/quetzalstock_specifications.pdf](url)
Estas mismas están en desarrollo para su uso en el proyecto.
